spring.application.name=exemplo5

spring.datasource.url=jdbc:h2:mem:bancoteste
spring.h2.console.enabled=true

# Configuração do H2 para o codespaces
spring.h2.console.settings.web-allow-others=true
server.forward-headers-strategy=framework